[tool.poetry]
name = "scrapers_searchs"
version = "0.1.0"
description = "Merkiso Scrapers"
authors = ["German Castellanos <germancodeg@gmail.com>"]
readme = "README.md"

[project]
name = "scrapers_searchs"
authors = [{ name = "German Castellanos", email = "germancodeg@gmail.com" }]
dependencies = [
    "Scrapy==2.10.1",
]

description = "Merkiso Scrapers"
requires-python = ">=3.9"


dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "__version__" }