[tool.poetry]
name = "app"
version = "0.1.0"
description = "Merkiso Scrapers"
authors = ["German Castellanos <germancodeg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
scrapy = "^2.5.0"
twisted = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
